# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Sialah' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sialah
  pod 'CTPanoramaView'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

end
